export const HANDLE_CHANGE_SELECTED_COUNTRY = 'HANDLE_CHANGE_SELECTED_COUNTRY';
export const SET_SELECTED_COUNTRY = 'SET_SELECTED_COUNTRY';
export const FETCH_COUNTRIES = 'FETCH_COUNTRIES';
export const SET_AVAILABLE_COUNTRIES = 'SET_AVAILABLE_COUNTRIES';
export const FETCH_COUNTRY_DATA = 'FETCH_COUNTRY_DATA';
export const SET_COUNTRY_DATA = 'SET_COUNTRY_DATA';

export const API = 'https://api.covid19api.com';
export const FETCH_COUNTRIES_URL = `${API}/countries`;
